### ISSUE TITLE
addition

### ISSUE THREAD

**Issue by huaji0353** [SerialLain3170/awesome-animeresearch#1]
Sketch2anime : [SmartPaint: a co-creative drawing system based on generative adversarial networks](https://link.springer.com/article/10.1631/FITEE.1900386)
Sketch2anime : [PI-REC: Progressive Image Reconstruction Network With Edge and Color Domain](https://arxiv.org/pdf/1903.10146.pdf)

**Comment by SerialLain3170** [comment]
Thanks for providing information! I added these papers.
